apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pubsec-info-assistant

resources:
- backend-deployment.yaml
- frontend-deployment.yaml
- statefulsets.yaml
- services.yaml
- configmap.yaml
- ingress.yaml
- hpa.yaml
- pdb.yaml
- network-policy.yaml

commonLabels:
  app: pubsec-info-assistant
  managed-by: kustomize

images:
- name: ghcr.io/eva-suite/eva-da-2/backend
  newTag: latest
- name: ghcr.io/eva-suite/eva-da-2/frontend
  newTag: latest
